language: node_js
node_js:
  - '16'

branches:
  only:
    - master

script:
  - npm install
  - npm run build

before_deploy:
  - mkdir -p before-deploy
  - cp -r build/* before-deploy/
  - cp appspec.yml before-deploy/
  - cp scripts/*.sh before-deploy/
  - cd before-deploy
  - zip -r first-project-react *
  - cd ../ && mkdir -p deploy 
  - mv before-deploy/first-project-react.zip deploy/first-project-react.zip
  - cd ..

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: first-project-react-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: first-project-react-build
    key: first-project-react.zip
    bundle_type: zip
    application: first-project-react
    deployment_group: first-project-react-group
    region: ap-northeast-2
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - popopqo777@gmail.com
    on_success: always
    on_failure: always
