language: node_js
node_js:
  - '16'

branches:
  only:
    - master

cache:
  directories:
    - node_modules

notifications:
  email:
    recipients:
      - popopqo777@gmail.com
    on_success: always
    on_failure: always
